# Generated by Django 4.2.11 on 2026-02-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurnPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('subscription_duration_months', models.IntegerField()),
                ('contract_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Annual', 'Annual')], max_length=20)),
                ('monthly_logins', models.IntegerField()),
                ('last_purchase_days_ago', models.IntegerField()),
                ('app_usage_time_min', models.FloatField()),
                ('monthly_spend', models.FloatField()),
                ('discount_usage_percentage', models.FloatField()),
                ('customer_support_calls', models.IntegerField()),
                ('satisfaction_score', models.IntegerField()),
                ('is_churn', models.BooleanField()),
                ('churn_probability', models.FloatField()),
                ('risk_level', models.CharField(max_length=20)),
                ('customer_id', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
