# Generated by Django 6.0.2 on 2026-02-23 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50, unique=True)),
                ('age', models.IntegerField()),
                ('subscription_duration_months', models.IntegerField()),
                ('contract_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Annual', 'Annual')], max_length=20)),
                ('monthly_logins', models.IntegerField()),
                ('last_purchase_days_ago', models.IntegerField()),
                ('app_usage_time_min', models.FloatField()),
                ('monthly_spend', models.FloatField()),
                ('discount_usage_percentage', models.FloatField()),
                ('customer_support_calls', models.IntegerField()),
                ('satisfaction_score', models.IntegerField()),
                ('actual_churn', models.BooleanField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['customer_id'],
            },
        ),
        migrations.RenameField(
            model_name='churnprediction',
            old_name='customer_id',
            new_name='customer_ref_id',
        ),
        migrations.AddField(
            model_name='churnprediction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='modelapp.customer'),
        ),
    ]
