# Generated by Django 6.0.2 on 2026-02-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0002_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churnprediction',
            name='customer_ref_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='churnprediction',
            name='is_churn',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='churnprediction',
            name='risk_level',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
